site_name: Retail AI Documentation
site_description: Comprehensive documentation for the Retail AI multi-agent system
site_author: Retail AI Team
site_url: https://your-domain.github.io/retail-ai

# Repository
repo_name: retail-ai
repo_url: https://github.com/your-org/retail-ai
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - mermaid2:
      arguments:
        theme: auto

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - MkDocs Guide: getting-started/mkdocs-quickstart.md
  - Architecture:
    - Overview: architecture/overview.md
  - Tools:
    - Overview: tools/overview.md
    - Unity Catalog Functions: tools/unity-catalog-functions.md
  - Applications:
    - Streamlit App: applications/streamlit-app.md
  - Deployment:
    - Production: deployment/production.md
  - Development:
    - Contributing: development/contributing.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/retail-ai
  version:
    provider: mike 