catalog_name: nfleming
database_name: retail_ai
volume_name: retail_ai
users: []

llms:
  model_name: databricks-meta-llama-3-3-70b-instruct

app:
  registered_model_name: nfleming.retail_ai.retail_ai_agent    
  endpoint_name: retail_ai_agent
  tags:
    business: retail
    streaming: true
    purpose: demo
    endpointSource: playground
  example_input:
    messages:
      - role: user
        content: Can you recommend a lamp to match my oak side tables?
    custom_inputs:
      configurable:
        thread_id: "1"
        tone: pirate
  recommendation_example:
    messages:
      - role: user
        content: Can you recommend a lamp to match my oak side tables?
    custom_inputs:
      configurable:
        thread_id: "1"
        tone: pirate
  inventory_example:
    messages:
      - role: user
        content: How many oak tables do we have in stock?
    custom_inputs:
      configurable:
        thread_id: "1"
        tone: pirate

checkpointer:
  connection_url: postgresql://postgres:postgres@localhost:5442/postgres?sslmode=disable
  connection_kwargs:
    autocommit: True
    prepare_threshold: 0

evaluation:
  model_name: databricks-meta-llama-3-3-70b-instruct
  table_name: nfleming.retail_ai.wands_evaluation
  num_evals: 10

genie:
  space_id: 01f01c91f1f414d59daaefd2b7ec82ea

functions:
  - nfleming.retail_ai.find_wands_product_by_id
  - system.ai.python_exec

retriever:
  embedding_model_endpoint_name: databricks-gte-large-en
  endpoint_name: one-env-shared-endpoint-12
  endpoint_type: STANDARD
  index_name: nfleming.retail_ai.wands_index
  primary_key: id
  doc_uri: doc_uri
  embedding_source_column: content
  columns:
    - product_id
    - product_name
    - product_class
    - category_hierarchy
    - rating_count
    - average_rating
    - review_count
    - doc_uri
  search_parameters:
    num_results: 10
    filter: {}
    query_type: ANN

agents:

  supervisor:
    model_name: databricks-meta-llama-3-3-70b-instruct

  image_summarization:
    model_name: databricks-meta-llama-3-3-70b-instruct
    
  inventory:
    model_name: databricks-meta-llama-3-3-70b-instruct


  order_status:
    model_name: databricks-meta-llama-3-3-70b-instruct

  recommendation:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      You are an AI assistant specializing in making recommendations about pairing items

      #### Tone: 
      {tone}

      #### Context:
      {context}

      #### Instructions:
      {content}
      
      Now, draft the response accordingly.

datasets:
  huggingface:
    - repo_id: napsternxg/wands
      primary_key: id
      table_name: nfleming.retail_ai.wands
    - url: https://raw.githubusercontent.com/wayfair/WANDS/refs/heads/main/dataset/product.csv
      primary_key: product_id
      table_name: nfleming.retail_ai.wands_product
    - url: https://raw.githubusercontent.com/wayfair/WANDS/refs/heads/main/dataset/label.csv
      primary_key: id
      table_name: nfleming.retail_ai.wands_label  
    - url: https://raw.githubusercontent.com/wayfair/WANDS/refs/heads/main/dataset/query.csv
      primary_key: query_id
      table_name: nfleming.retail_ai.wands_query


