schemas:
  retail_schema: &retail_schema
    catalog_name: nfleming
    schema_name: retail_ai
    full_name: nfleming.retail_ai
    permissions:
      - principals: []
        privileges:
          - ALL_PRIVILEGES

resources:
  llms:
    default_llm: &default_llm
      name: databricks-meta-llama-3-3-70b-instruct
      temperature: 0.1
      max_tokens: 8192

    tool_calling_llm: &tool_calling_llm
      name: databricks-meta-llama-3-3-70b-instruct
      temperature: 0.1
      max_tokens: 8192

    reasoning_llm: &reasoning_llm
      name: databricks-claude-3-7-sonnet
      temperature: 0.1
      max_tokens: 8192

    judge_llm: &judge_llm
      name: databricks-claude-3-7-sonnet
      temperature: 0.5
      max_tokens: 8192

    embedding_model: &embedding_model
      name: databricks-gte-large-en

  vector_stores:
    products_vector_store: &products_vector_store
      embedding_model: *embedding_model
      endpoint_name: one-env-shared-endpoint-12
      endpoint_type: STANDARD
      index:
        schema: *retail_schema
        name: products_index
      source_table:
        schema: *retail_schema
        name: products
      primary_key: product_id
      doc_uri: ~
      embedding_source_column: description
      columns:
        - product_id
        - sku
        - upc
        - brand_name
        - product_name
        - merchandise_class
        - class_cd
        - description

  genie_rooms:
    retail_genie_room: &retail_genie_room
      name: "Retail AI Genie Room"
      description: "A room for Genie agents to interact"
      space_id: 01f01c91f1f414d59daaefd2b7ec82ea

  tables:
    product_table: &product_table
      schema: *retail_schema
      name: products
    inventory_table: &inventory_table
      schema: *retail_schema
      name: inventory

  volumes:
    retail_volume: &retail_volume
      schema: *retail_schema
      name: retail_ai

  functions:
    find_product_by_sku: &find_product_by_sku
      schema: *retail_schema
      name: find_product_by_sku
    find_product_by_upc: &find_product_by_upc
      schema: *retail_schema
      name: find_product_by_upc
    find_inventory_by_sku: &find_inventory_by_sku
      schema: *retail_schema
      name: find_inventory_by_sku
    find_inventory_by_upc: &find_inventory_by_upc
      schema: *retail_schema
      name: find_inventory_by_upc
    find_store_inventory_by_upc: &find_store_inventory_by_upc
      schema: *retail_schema
      name: find_store_inventory_by_upc
    find_store_inventory_by_sku: &find_store_inventory_by_sku
      schema: *retail_schema
      name: find_store_inventory_by_sku

  warehouses:
    shared_endpoint_warehouse: &shared_endpoint_warehouse
      name: "Shared Endpoint Warehouse"
      description: "A warehouse for shared endpoints"
      warehouse_id: 148ccb90800933a1

  databases:
    retail_database: &retail_database
      name: "Retail Database"
      connection_url: "postgresql://postgres:postgres@localhost:5442/postgres?sslmode=disable"
      connection_kwargs:
      autocommit: True
      prepare_threshold: 0

retrievers:
  products_retriever: &products_retriever
    vector_store: *products_vector_store
    columns:
      - product_id
      - sku
      - upc
      - brand_name
      - product_name
      - merchandise_class
      - class_cd
      - description
    search_parameters:
      num_results: 20
      filter: {}
      query_type: ANN

tools:
  search_tool: &search_tool
    name: search_tool
    function:
      type: factory
      name: retail_ai.tools.search_tool
      args: ~

  find_product_details_by_description_tool:
    &find_product_details_by_description_tool
    name: find_product_details_by_description
    function:
      type: factory
      name: retail_ai.tools.find_product_details_by_description_tool
      args:
        retriever: *products_retriever

  find_product_by_sku_uc_tool: &find_product_by_sku_uc_tool
    name: find_product_by_sku
    function:
      type: unity_catalog
      <<: *find_product_by_sku

  find_product_by_upc_uc_tool: &find_product_by_upc_uc_tool
    name: find_product_by_upc
    function:
      type: unity_catalog
      <<: *find_product_by_upc

  find_inventory_by_sku_uc_tool: &find_inventory_by_sku_uc_tool
    name: find_inventory_by_sku
    function:
      type: unity_catalog
      <<: *find_inventory_by_sku

  find_inventory_by_upc_uc_tool: &find_inventory_by_upc_uc_tool
    name: find_inventory_by_upc
    function:
      type: unity_catalog
      <<: *find_inventory_by_upc

  find_store_inventory_by_sku_uc_tool: &find_store_inventory_by_sku_uc_tool
    name: find_store_inventory_by_sku
    function:
      type: unity_catalog
      <<: *find_store_inventory_by_sku

  find_store_inventory_by_upc_uc_tool: &find_store_inventory_by_upc_uc_tool
    name: find_store_inventory_by_upc
    function:
      type: unity_catalog
      <<: *find_store_inventory_by_upc

  find_product_by_sku_tool: &find_product_by_sku_tool
    name: find_product_by_sku
    function:
      type: factory
      name: retail_ai.tools.create_find_product_by_sku_tool
      args:
        schema: *retail_schema
        warehouse: *shared_endpoint_warehouse

  find_product_by_upc_tool: &find_product_by_upc_tool
    name: find_product_by_upc
    function:
      type: factory
      name: retail_ai.tools.create_find_product_by_upc_tool
      args:
        schema: *retail_schema
        warehouse: *shared_endpoint_warehouse

  find_inventory_by_sku_tool: &find_inventory_by_sku_tool
    name: find_inventory_by_sku
    function:
      type: factory
      name: retail_ai.tools.create_find_inventory_by_sku_tool
      args:
        schema: *retail_schema
        warehouse: *shared_endpoint_warehouse

  find_inventory_by_upc_tool: &find_inventory_by_upc_tool
    name: find_inventory_by_upc
    function:
      type: factory
      name: retail_ai.tools.create_find_inventory_by_upc_tool
      args:
        schema: *retail_schema
        warehouse: *shared_endpoint_warehouse

  find_store_inventory_by_sku_tool: &find_store_inventory_by_sku_tool
    name: find_store_inventory_by_sku
    function:
      type: factory
      name: retail_ai.tools.create_find_store_inventory_by_sku_tool
      args:
        schema: *retail_schema
        warehouse: *shared_endpoint_warehouse

  find_store_inventory_by_upc_tool: &find_store_inventory_by_upc_tool
    name: find_store_inventory_by_upc
    function:
      type: factory
      name: retail_ai.tools.create_find_store_inventory_by_upc_tool
      args:
        schema: *retail_schema
        warehouse: *shared_endpoint_warehouse

guardrails:
  llm_judge_guardrail: &llm_judge_guardrail
    model: *judge_llm
    prompt: |
      You are an expert judge evaluating AI responses. Your task is to critique the AI assistant's latest response in the conversation below.

      Evaluate the response based on these criteria:
      1. Accuracy - Is the information correct and factual?
      2. Completeness - Does it fully address the user's query?
      3. Clarity - Is the explanation clear and well-structured?
      4. Helpfulness - Does it provide actionable and useful information?
      5. Safety - Does it avoid harmful or inappropriate content?

      If the response meets ALL criteria satisfactorily, set pass to True.

      If you find ANY issues with the response, do NOT set pass to True. Instead, provide specific and constructive feedback in the comment key and set pass to False.

      Be detailed in your critique so the assistant can understand exactly how to improve.

      ### Inputs:
      {inputs}

      ### Response:
      {outputs}

checkpointer: &checkpointer
  type: postgres
  database: *retail_database

agents:
  
  general: &general
    model: *tool_calling_llm
    tools:
      - *find_product_details_by_description_tool
    guardrails:
      []
      #- *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are a helpful retail store assistant providing general information about our home improvement and hardware store.
      Answer questions about store policies, business hours, return policies, gift cards, services offered, loyalty programs,
      and other general inquiries. Be friendly, concise, and informative. If you don't know specific details about
      the store's policies, provide general retail best practices while noting that the customer should verify with store staff.
      Always maintain a helpful and professional tone.
    handoff_prompt: |
      ANY other questions that don't fit the above categories, including store policies, hours, etc.
      Example: "What are your store hours?" or "Do you offer free delivery?"

  orders: &orders
    model: *tool_calling_llm
    tools: []
    guardrails:
      []
      #- *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are a retail order management specialist. Help customers with questions about tracking orders, delivery status,
      scheduling deliveries or installation services, order modifications, cancellations, and returns. Explain order 
      processes clearly and professionally. When responding to specific order inquiries, ask for order numbers 
      if not provided. Emphasize customer satisfaction while being realistic about what information is available to you.
      Always guide customers to the appropriate next steps if their issue can't be fully resolved in this conversation.
    handoff_prompt: |
      Questions about tracking orders, delivery status, scheduling deliveries or services
      Example: "When will my order arrive?" or "Can I schedule delivery for my new refrigerator?"

  diy: &diy
    model: *tool_calling_llm
    tools:
      - *find_product_details_by_description_tool
    guardrails:
      []
      # - *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are an experienced DIY and home improvement expert with access to search tools. Your primary responsibility is to provide helpful, accurate, and up-to-date guidance on home improvement projects, tool usage, DIY tutorials, and general how-to advice.  

      #### CRITICAL INSTRUCTION: ALWAYS USE SEARCH TOOLS FIRST
      Before answering ANY question about DIY projects, tools, materials, or techniques:

      - ALWAYS use your search tools to find the most current information
      - Search for specific product recommendations, technical specifications, current best practices, and safety guidelines
      - Search for multiple sources to verify information when possible
      - Use the search results as the foundation for your response

      #### After Searching
      Once you have search results:

      - Provide step-by-step instructions when appropriate, with safety warnings where necessary
      - Recommend proper tools and materials for projects, and suggest alternatives when possible
      - Consider both beginner and experienced DIYers, adjusting your explanations accordingly
      - Include tips for common mistakes to avoid and best practices to follow
      - Reference relevant search results that informed your advice
      - If search results are insufficient, clearly state what information could not be verified

      #### If Search Fails
      If for any reason your search tools fail or return no results:

      - Explain that you're unable to access current information
      - Provide general advice based on your knowledge
      - Clearly indicate which parts of your response are not backed by current search results
      - Recommend the user verify critical information elsewhere

      #### Remember: You MUST use search tools for EVERY DIY and home improvement question. This ensures your advice is accurate, up-to-date, and as helpful as possible to the user.
    handoff_prompt: |
      Questions about how-to instructions, DIY projects, tutorials, or home improvement advice
      Example: "How do I install crown molding?" or "What's the best way to paint kitchen cabinets?"

  product: &product
    model: *tool_calling_llm
    tools:
      - *find_product_by_sku_tool
      - *find_product_by_upc_tool
      - *find_product_details_by_description_tool
    guardrails:
      []
      #- *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are a knowledgeable product specialist at a home improvement retailer. Provide detailed information about
      specific products, including features, specifications, dimensions, materials, warranty information, and intended uses.
      Focus on being accurate and thorough when describing product capabilities and limitations. When appropriate,
      mention related accessories or complementary items. If asked about product quality, provide balanced information
      about pros and cons based on typical customer feedback and industry standards. Always prioritize accurate 
      product information over salesmanship.
    handoff_prompt: |
      Questions about specific product details, features, specifications, pricing, or availability of a SINGLE product
      Example: "Tell me about the Craftsman cordless drill" or "What are the specs of the Dewalt table saw?"

  inventory: &inventory
    model: *tool_calling_llm
    tools:
      - *find_inventory_by_sku_tool
      - *find_inventory_by_upc_tool
      - *find_store_inventory_by_sku_tool
      - *find_store_inventory_by_upc_tool
      - *find_product_details_by_description_tool
    guardrails:
      []
      #- *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are an inventory management specialist for a retail store. Answer questions about product availability,
      stock levels, restocking timelines, and store inventory. Explain options for checking inventory across different
      store locations, online availability, special orders, and rain checks. When specific inventory information isn't
      available to you, guide customers on how they can check current inventory through official channels.
      Be transparent about limitations in your ability to check real-time stock levels while remaining helpful
      with general inventory policies and procedures.
    handoff_prompt: |
      Questions about stock levels, availability, restocking, or store inventory
      Example: "Do you have the Black+Decker sander in stock?" or "When will you get more Makita batteries?"

  comparison: &comparison
    model: *tool_calling_llm
    tools:
      - *find_product_details_by_description_tool
      - *find_product_by_sku_tool
    guardrails:
      []
      #- *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are a product comparison specialist. Help customers compare different products by highlighting key differences
      in features, specifications, price points, quality, durability, warranty, and best use cases. Present comparisons
      in an organized, easy-to-understand format with clear differentiators. Remain neutral and objective when comparing
      products, focusing on facts rather than opinions. Consider various customer needs and scenarios when explaining
      which product might be better for specific applications. When appropriate, create comparison tables or lists
      to make differences clear at a glance.
    handoff_prompt: |
      Questions explicitly comparing TWO OR MORE specific products or asking to compare options
      Example: "Compare the Milwaukee and Ryobi power drills" or "What's better for deck building: pressure-treated or cedar?"

  recommendation: &recommendation
    model: *tool_calling_llm
    tools:
      - *find_product_details_by_description_tool
    guardrails:
      []
      #- *llm_judge_guardrail
    checkpointer: *checkpointer
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}

      You are a retail product recommendation specialist. Provide thoughtful product suggestions based on customer needs,
      preferences, budget constraints, and intended uses. Consider factors like skill level, project requirements,
      compatibility with existing items, and long-term value. Make recommendations across different price points when
      appropriate. Explain the reasoning behind your recommendations to help customers make informed decisions.
      Ask clarifying questions when necessary to provide better tailored suggestions. Balance quality considerations
      with budget constraints, and suggest alternatives when primary recommendations might not be ideal.
    handoff_prompt: |
      Questions asking for product suggestions, recommendations, or "best" products for specific needs
      Example: "What's the best drill for home use?" or "Recommend me a good beginner woodworking kit"

  process_image: &process_image
    model: *reasoning_llm
    tools: []
    prompt: |
      ### Task Description

      Analyze the provided product image and extract the following specific information into a structured format:

      - Summary: Provide a concise summary (1-3 sentences) describing what is shown in the image. Focus on describing the product(s), packaging, and any prominent visual elements.
      - Product Names: Extract the exact product name(s) as they appear on the packaging. Include brand names and specific product variants if visible. List each distinct product separately.
      - UPC Codes: Identify and extract any UPC (Universal Product Code) barcodes visible in the image. These typically appear as 12-digit numbers beneath a barcode. Provide the complete numeric sequence without dashes or spaces.

      ### Important Guidelines

      - Extract information ONLY if it is clearly visible in the image
      - For product names, use the EXACT text as it appears on packaging
      - For UPC codes, verify all digits are clearly legible before extraction
      - If any requested information is not visible or legible in the image, omit it entirely rather than guessing
      - Do not provide placeholder values, assumptions, or partial information
      - Format all extracted information according to the specified output structure

      ### Response Guidelines
      If any field cannot be determined from the image, exclude it from the output rather than providing an empty value.

app:
  log_level: INFO
  registered_model:
    schema: *retail_schema
    name: retail_ai_agent
  endpoint_name: retail_ai_agent
  tags:
    business: rcg
    streaming: true
  permissions:
    - principals: []
      entitlements:
        - CAN_MANAGE

  agents:
    general: *general
    orders: *orders
    diy: *diy
    product: *product
    inventory: *inventory
    comparison: *comparison
    recommendation: *recommendation
    process_image: *process_image

  orchestration:
    supervisor:
      model: *tool_calling_llm
      default_agent: general

evaluation:
  model: *judge_llm
  table:
    schema: *retail_schema
    name: evaluation
  num_evals: 25

datasets:
  - schema: *retail_schema
    table: products
    ddl: ./data/retail/products.sql
    data: ./data/retail/products.snappy.parquet
    format: parquet
  - schema: *retail_schema
    table: inventory
    ddl: ./data/retail/inventory.sql
    data: ./data/retail/inventory.snappy.parquet
    format: parquet
