
catalog_name: nfleming
database_name: retail_ai
volume_name: retail_ai
permissions:
  - principals: []
    privileges:
      - ALL_PRIVILEGES

llms:
  model_name: databricks-meta-llama-3-3-70b-instruct
  #model_name: databricks-claude-3-7-sonnet

app:
  log_level: INFO
  registered_model_name: nfleming.retail_ai.retail_ai_agent    
  endpoint_name: retail_ai_agent
  tags:
    business: retail
    streaming: true
    purpose: demo
    endpointSource: playground

  permissions:
    - principals: []
      entitlements:
        - CAN_MANAGE

  examples:

    recommendation_example:
      messages:
        - role: user
          content: Can you recommend a lamp to match my oak side tables?
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    inventory_example:
      messages:
        - role: user
          content: How many oak tables do we have in stock?
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    comparison_example:
      messages:
        - role: user
          content: Can you compare items with product ids 14523 and 25163
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    general_example:
      messages:
        - role: user
          content: Can you answer this general question about your billing process?
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    diy_example:
      messages:
        - role: user
          content: Can you tell me how to fix a leaky faucet?
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    orders_example:
      messages:
        - role: user
          content: Can you give me an update on my order. The order number is 12345
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    product_example:
      messages:
        - role: user
          content: Can you give me information about the Big Green Egg grill?
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

    product_image_example:
      messages:
        - role: user
          content: 
            - type: text
              text: Can you give me information about this item?
            - type: image_url
              image_url:
                url: https://cdn.sanity.io/images/hdptt806/production/7ff02721909ac66133ae094c80f3e8ba2d5befc5-2270x3469.jpg?w=340&auto=format
      custom_inputs:
        configurable:
          thread_id: "1"
          user_id: nate.fleming
          store_num: 123
          scd_ids:
            - "1"
            - "2"
            - "3"

checkpointer:
  connection_url: postgresql://postgres:postgres@localhost:5442/postgres?sslmode=disable
  connection_kwargs:
    autocommit: True
    prepare_threshold: 0

evaluation:
  model_name: databricks-meta-llama-3-3-70b-instruct
  table_name: nfleming.retail_ai.wands_evaluation
  num_evals: 10

genie:
  space_id: 01f01c91f1f414d59daaefd2b7ec82ea

tables:
  - nfleming.retail_ai.wands
  - nfleming.retail_ai.wands_product

functions:
  - nfleming.retail_ai.find_product_by_sku

retriever:
  embedding_model_endpoint_name: databricks-gte-large-en
  endpoint_name: one-env-shared-endpoint-12
  endpoint_type: STANDARD
  index_name: nfleming.retail_ai.wands_index
  primary_key: product_id
  doc_uri: doc_uri
  embedding_source_column: content
  columns:
    - product_id
    - product_name
    - product_class
    - category_hierarchy
    - rating_count
    - average_rating
    - review_count
    - doc_uri
  search_parameters:
    num_results: 10
    filter: {}
    query_type: ANN

agents:

  router:
    model_name: databricks-meta-llama-3-3-70b-instruct
    allowed_routes:
      - product
      - comparison
      - recommendation
      - inventory
      - diy
      - orders
      - general
    default_route: general
    prompt: |
      Analyze the user question and select ONE specific route from the allowed options:
      
      - Route to 'product': Questions about specific product details, features, specifications, pricing, or availability of a SINGLE product
        Example: "Tell me about the Craftsman cordless drill" or "What are the specs of the Dewalt table saw?"
      
      - Route to 'comparison': Questions explicitly comparing TWO OR MORE specific products or asking to compare options
        Example: "Compare the Milwaukee and Ryobi power drills" or "What's better for deck building: pressure-treated or cedar?"
      
      - Route to 'recommendation': Questions asking for product suggestions, recommendations, or "best" products for specific needs
        Example: "What's the best drill for home use?" or "Recommend me a good beginner woodworking kit"
      
      - Route to 'inventory': Questions about stock levels, availability, restocking, or store inventory
        Example: "Do you have the Black+Decker sander in stock?" or "When will you get more Makita batteries?"
      
      - Route to 'diy': Questions about how-to instructions, DIY projects, tutorials, or home improvement advice
        Example: "How do I install crown molding?" or "What's the best way to paint kitchen cabinets?"
      
      - Route to 'orders': Questions about tracking orders, delivery status, scheduling deliveries or services
        Example: "When will my order arrive?" or "Can I schedule delivery for my new refrigerator?"

      - Route to 'general': ANY other questions that don't fit the above categories, including store policies, hours, etc.
        Example: "What are your store hours?" or "Do you offer free delivery?"
      
      Choose exactly ONE route that BEST matches the user's primary intent.


  general:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are a helpful retail store assistant providing general information about our home improvement and hardware store.
      Answer questions about store policies, business hours, return policies, gift cards, services offered, loyalty programs,
      and other general inquiries. Be friendly, concise, and informative. If you don't know specific details about
      the store's policies, provide general retail best practices while noting that the customer should verify with store staff.
      Always maintain a helpful and professional tone.

  orders:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are a retail order management specialist. Help customers with questions about tracking orders, delivery status,
      scheduling deliveries or installation services, order modifications, cancellations, and returns. Explain order 
      processes clearly and professionally. When responding to specific order inquiries, ask for order numbers 
      if not provided. Emphasize customer satisfaction while being realistic about what information is available to you.
      Always guide customers to the appropriate next steps if their issue can't be fully resolved in this conversation.

  diy:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are an experienced DIY and home improvement expert. Provide helpful guidance on home improvement projects,
      tool usage, DIY tutorials, and general how-to advice. Offer step-by-step instructions when appropriate, with
      safety warnings where necessary. Recommend proper tools and materials for projects, and suggest alternatives
      when possible. Consider both beginner and experienced DIYers in your responses, adjusting your explanations
      accordingly. Include tips for common mistakes to avoid and best practices to follow.

      Use the tools provide to give the most up to date response
      

  product:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are a knowledgeable product specialist at a home improvement retailer. Provide detailed information about
      specific products, including features, specifications, dimensions, materials, warranty information, and intended uses.
      Focus on being accurate and thorough when describing product capabilities and limitations. When appropriate,
      mention related accessories or complementary items. If asked about product quality, provide balanced information
      about pros and cons based on typical customer feedback and industry standards. Always prioritize accurate 
      product information over salesmanship.

  inventory:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are an inventory management specialist for a retail store. Answer questions about product availability,
      stock levels, restocking timelines, and store inventory. Explain options for checking inventory across different
      store locations, online availability, special orders, and rain checks. When specific inventory information isn't
      available to you, guide customers on how they can check current inventory through official channels.
      Be transparent about limitations in your ability to check real-time stock levels while remaining helpful
      with general inventory policies and procedures.

  comparison:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are a product comparison specialist. Help customers compare different products by highlighting key differences
      in features, specifications, price points, quality, durability, warranty, and best use cases. Present comparisons
      in an organized, easy-to-understand format with clear differentiators. Remain neutral and objective when comparing
      products, focusing on facts rather than opinions. Consider various customer needs and scenarios when explaining
      which product might be better for specific applications. When appropriate, create comparison tables or lists
      to make differences clear at a glance.

  recommendation:
    model_name: databricks-meta-llama-3-3-70b-instruct
    prompt: |
      ### User Information
      - **User Id**: {user_id}
      - **Store Number**: {store_num}
      
      You are a retail product recommendation specialist. Provide thoughtful product suggestions based on customer needs,
      preferences, budget constraints, and intended uses. Consider factors like skill level, project requirements,
      compatibility with existing items, and long-term value. Make recommendations across different price points when
      appropriate. Explain the reasoning behind your recommendations to help customers make informed decisions.
      Ask clarifying questions when necessary to provide better tailored suggestions. Balance quality considerations
      with budget constraints, and suggest alternatives when primary recommendations might not be ideal.

  process_image:
    model_name: databricks-claude-3-7-sonnet
    prompt: |
      You are a visual product summarization assistant. Your task is to analyze an image and generate a structured summary based on the contents of the scene.
      Your output must include the following:
      A brief summary of the scene (what is visually present).
      A list of all identifiable products in the image, including:
      Product name
      SKU number (if visible or extractable)

